#!/usr/bin/env python3
"""SWORD mechanics rig: a stand-in server for generated-test plumbing.

!!! THIS IS NOT WEKO. It proves nothing about WEKO's behaviour. !!!

It exists so that tests generated by the hub (multipart upload, omitted
headers, bearer tokens, assertions on error JSON, evidence files with masking,
browser steps, helper and docker calls) can be run mechanically in an
environment where WEKO cannot be started. Every response carries the header
`X-Stub: sword-mechanics-rig`.

The order of the checks follows `weko_swordserver/views.py` and
`decorators.py` on the WEKO branch `test/sword-error-codes`; the error bodies,
statuses and messages follow `errors.py` (see errtable.py). Anything the
stand-in has to invent (how a package is parsed, what a status document
contains) is a guess and is documented in docs/stub.md.

Standard library only (Python 3.11).

    python tools/sword-stub/stub_server.py --config stub.json --log-file app.log --port 0
"""

from __future__ import annotations

import argparse
import copy
import csv
import hashlib
import io
import json
import re
import sys
import threading
import time
import traceback
import urllib.parse
import uuid
import zipfile
from datetime import UTC, datetime
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

import errtable  # noqa: E402

BANNER = (
    "*** sword-stub: MECHANICS RIG ONLY. This is NOT WEKO and proves nothing about "
    "WEKO's behaviour. ***"
)
STUB_HEADER = ("X-Stub", "sword-mechanics-rig")
CONTROL_PREFIX = "/__stub__/"
ADMIN_PREFIX = "/stub-admin"

PKG_SIMPLEZIP = "http://purl.org/net/sword/3.0/package/SimpleZip"
PKG_BAGIT = "http://purl.org/net/sword/3.0/package/SWORDBagIt"
SWORD_METADATA_FILE = "metadata/sword.json"
ROCRATE_METADATA_FILE = "data/ro-crate-metadata.json"

SCOPE_WRITE = "deposit:write"
SCOPE_ACTIONS = "deposit:actions"
SCOPE_CREATE = "item:create"
SCOPE_UPDATE = "item:update"
SCOPE_DELETE = "item:delete"
SCOPE_ACTIVITY = "user:activity"

MAX_READ_BYTES = 256 * 1024 * 1024
"""Bodies larger than this are not read; the size check answers from the header."""

DEFAULT_CONFIG: dict[str, Any] = {
    "tokens": {},
    "revoked": [],
    "clients": {},
    "records": {},
    "next_recid": 100,
    "users": {},
    "containers": {
        "web": "weko-web-1",
        "db": "weko-db-1",
        "redis": "weko-redis-1",
        "search": "weko-es-1",
    },
    "admin": {"user": "admin", "password": "stub-admin-pass"},
    "settings": {
        "on_behalf_of": False,
        "obo_users": {},
        "max_upload_size": 15 * 1024**3,
        "accept_archive_format": ["application/zip", "multipart/form-data"],
        "accept_packaging": ["*"],
        "digest_verification": True,
        "import_enabled": {"TSV/CSV": True, "XML": True, "JSON": True},
        "roles_allowed": ["System Administrator", "Repository Administrator"],
        "rate_limit": None,
        "lock_seconds": 0,
        "faithful_log": True,
        "location_header": True,
    },
}


def utc_now() -> datetime:
    return datetime.now(UTC)


def iso(ts: datetime) -> str:
    return ts.strftime("%Y-%m-%dT%H:%M:%S.") + f"{ts.microsecond // 1000:03d}Z"


def _merge(base: dict[str, Any], extra: dict[str, Any]) -> dict[str, Any]:
    out = copy.deepcopy(base)
    for key, value in extra.items():
        if (
            isinstance(value, dict)
            and isinstance(out.get(key), dict)
            and key
            in (
                "settings",
                "containers",
                "admin",
            )
        ):
            out[key].update(copy.deepcopy(value))
        else:
            out[key] = copy.deepcopy(value)
    return out


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class SwordError(Exception):
    """A coded error (`WEKO_SWORDSERVER_E_xxxx`)."""

    def __init__(self, code: str, log: str | None = None, **params: object) -> None:
        type_, status, message = errtable.describe(code, **params)
        super().__init__(message)
        self.code, self.type, self.status, self.message = code, type_, status, message
        self.log = log


class PlainError(Exception):
    """401 / 403 without a WEKO code (the blueprint's generic handlers)."""

    def __init__(self, status: int) -> None:
        super().__init__(status)
        self.status = status


class DropConnection(Exception):
    """The web container is stopped: answer nothing."""


class Fault(Exception):
    """An injected failure with an optional fake traceback."""

    def __init__(self, code: str, source: str) -> None:
        super().__init__(code)
        self.code, self.source = code, source


# ---------------------------------------------------------------------------
# World (all mutable state)
# ---------------------------------------------------------------------------


class World:
    """Tokens, clients, records, faults and logs. One lock guards everything."""

    def __init__(self, config: dict[str, Any], log_file: str | None = None) -> None:
        self.lock = threading.RLock()
        self.initial = _merge(DEFAULT_CONFIG, config)
        self.log_file = log_file
        self.log_lines: list[str] = []
        self.log_times: list[datetime] = []
        self.db_log: list[str] = []
        self.rate_hits = 0
        self.reset(clear_log=True)

    # -- lifecycle --
    def reset(self, clear_log: bool = False) -> None:
        with self.lock:
            cfg = copy.deepcopy(self.initial)
            self.tokens: dict[str, dict[str, Any]] = cfg["tokens"]
            self.revoked: set[str] = set(cfg["revoked"])
            self.clients: dict[str, dict[str, Any]] = cfg["clients"]
            self.records: dict[str, dict[str, Any]] = {
                str(k): self._new_record(v) for k, v in cfg["records"].items()
            }
            self.next_recid: int = int(cfg["next_recid"])
            self.users: dict[str, dict[str, Any]] = cfg["users"]
            self.containers_cfg: dict[str, str] = cfg["containers"]
            self.admin: dict[str, str] = cfg["admin"]
            self.settings: dict[str, Any] = cfg["settings"]
            self.faults: list[dict[str, Any]] = []
            self.helper_faults: list[dict[str, Any]] = []
            self.stopped: set[str] = set()  # roles: web / db / redis / search
            self.redis: dict[str, tuple[str, float | None]] = {}
            self.deleted: list[str] = []
            self.rate_hits = 0
            self.minted = 0
            if clear_log:
                self.log_lines.clear()
                self.log_times.clear()
                self.db_log.clear()
                if self.log_file:
                    Path(self.log_file).write_text("", encoding="utf-8")

    @staticmethod
    def _new_record(data: dict[str, Any] | None = None) -> dict[str, Any]:
        rec = {
            "title": "Stub item",
            "doi": False,
            "locked": False,
            "editing": False,
            "importing": False,
            "version": 1,
            "locked_until": 0.0,
        }
        rec.update(data or {})
        return rec

    def role_of_container(self, name: str) -> str | None:
        for role, container in self.containers_cfg.items():
            if container == name:
                return role
        return None

    # -- logging --
    def log(self, level: str, message: str) -> None:
        """One application-log line. Never receives a secret."""
        now = utc_now()
        line = f"{iso(now)} {level} sword-stub: {message}"
        with self.lock:
            self.log_lines.append(line)
            self.log_times.append(now)
            if self.log_file:
                with open(self.log_file, "a", encoding="utf-8") as handle:
                    handle.write(line + "\n")

    def log_since(self, since: str | None) -> list[str]:
        with self.lock:
            lines = list(self.log_lines)
            if not since:
                return lines
            times = list(self.log_times)
        floor = _parse_ts(since)
        return [line for line, at in zip(lines, times, strict=True) if floor is None or at >= floor]

    # -- records --
    def allocate_recid(self) -> str:
        with self.lock:
            while str(self.next_recid) in self.records or str(self.next_recid) in self.deleted:
                self.next_recid += 1
            recid = str(self.next_recid)
            self.next_recid += 1
            return recid

    def state(self) -> dict[str, Any]:
        with self.lock:
            return {
                "stub": "sword-mechanics-rig",
                "tokens": {
                    t.get("name", "?"): {
                        "scopes": t.get("scopes", []),
                        "role": t.get("role"),
                        "client": t.get("client"),
                        "revoked": tok in self.revoked,
                    }
                    for tok, t in self.tokens.items()
                },
                "revoked": sorted(
                    self.tokens[t].get("name", "?") for t in self.revoked if t in self.tokens
                ),
                "clients": copy.deepcopy(self.clients),
                "records": copy.deepcopy(self.records),
                "deleted": list(self.deleted),
                "next_recid": self.next_recid,
                "faults": copy.deepcopy(self.faults),
                "helper_faults": copy.deepcopy(self.helper_faults),
                "stopped": sorted(self.stopped),
                "containers": dict(self.containers_cfg),
                "settings": copy.deepcopy(self.settings),
                "log_lines": len(self.log_lines),
            }


def _parse_ts(text: str) -> datetime | None:
    try:
        return datetime.fromisoformat(text.replace("Z", "+00:00")).astimezone(UTC)
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# Multipart
# ---------------------------------------------------------------------------


class Part:
    def __init__(
        self, name: str | None, filename: str | None, content_type: str | None, data: bytes
    ):
        self.name, self.filename, self.content_type, self.data = name, filename, content_type, data


_PARAM = r'{key}=(?:"((?:[^"\\]|\\.)*)"|([^;\s]*))'


def _disp_param(header: str, key: str) -> str | None:
    match = re.search(r"(?:^|[;\s])" + _PARAM.format(key=key), header, re.IGNORECASE)
    if match is None:
        return None
    return match.group(1) if match.group(1) is not None else (match.group(2) or "")


def parse_multipart(content_type: str, body: bytes) -> list[Part]:
    """Binary-safe multipart/form-data parser. Parts without a boundary are none."""
    match = re.search(r'boundary=(?:"([^"]+)"|([^;\s]+))', content_type or "", re.IGNORECASE)
    if not match or "multipart/" not in content_type.lower():
        return []
    boundary = (match.group(1) or match.group(2)).encode()
    delimiter = b"--" + boundary
    parts: list[Part] = []
    for chunk in body.split(delimiter)[1:]:
        if chunk.startswith(b"--"):
            break
        chunk = chunk[2:] if chunk.startswith(b"\r\n") else chunk
        head, sep, data = chunk.partition(b"\r\n\r\n")
        if not sep:
            continue
        if data.endswith(b"\r\n"):
            data = data[:-2]
        headers: dict[str, str] = {}
        for line in head.decode("utf-8", "replace").split("\r\n"):
            if ":" in line:
                k, v = line.split(":", 1)
                headers[k.strip().lower()] = v.strip()
        disposition = headers.get("content-disposition", "")
        parts.append(
            Part(
                _disp_param(disposition, "name"),
                _disp_param(disposition, "filename"),
                headers.get("content-type"),
                data,
            )
        )
    return parts


# ---------------------------------------------------------------------------
# Package inspection (the stub's own idea of what weko-swordserver looks at)
# ---------------------------------------------------------------------------


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _validate_bag(archive: zipfile.ZipFile) -> str | None:
    """Reason a BagIt bag is invalid, or None."""
    names = set(archive.namelist())
    if "bagit.txt" not in names:
        return "Bag is invalid: bagit.txt is missing"
    for manifest in ("manifest-sha256.txt", "tagmanifest-sha256.txt"):
        if manifest not in names:
            if manifest.startswith("manifest"):
                return f"Bag is invalid: {manifest} is missing"
            continue
        for line in archive.read(manifest).decode("utf-8", "replace").splitlines():
            if not line.strip():
                continue
            checksum, _, path = line.partition("  ")
            if path not in names:
                return f"Bag is invalid: {path} is listed in {manifest} but missing"
            if _sha256(archive.read(path)) != checksum.strip():
                return f"Bag is invalid: checksum mismatch for {path}"
    return None


def detect_format(archive: zipfile.ZipFile, packaging: str) -> str:
    """`check_import_file_format`: returns JSON / XML / TSV/CSV or raises SwordError."""
    files = archive.namelist()
    if "SWORDBagIt" in packaging:
        if SWORD_METADATA_FILE in files:
            return "JSON"
        raise SwordError("1404", log="metadate/sword.json is not found in SWORDBagIt.")
    if "SimpleZip" in packaging:
        if ROCRATE_METADATA_FILE in files:
            return "JSON"
        if SWORD_METADATA_FILE in files:
            raise SwordError("1405", log="packaging format is SimpleZip, but sword.json is found.")
        if any("ro-crate-metadata.json" in name for name in files):
            raise SwordError("1406")
        seconds = [n.split("/")[1] for n in files if "/" in n and n.split("/")[1]]
        if any(s.endswith(".xml") for s in seconds):
            return "XML"
        if any(s.endswith((".tsv", ".csv")) for s in seconds):
            return "TSV/CSV"
        raise SwordError("1407")
    raise SwordError("1408", packaging=packaging)


def _json_items(
    archive: zipfile.ZipFile, packaging: str
) -> tuple[list[dict[str, Any]], str | None]:
    """Items of a JSON-LD package, or (items, error detail)."""
    reason = _validate_bag(archive)
    if reason:
        return [], reason
    path = (
        SWORD_METADATA_FILE if SWORD_METADATA_FILE in archive.namelist() else ROCRATE_METADATA_FILE
    )
    raw = archive.read(path)
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        return [], f"{path} is not UTF-8 (byte offset {exc.start})"
    try:
        doc = json.loads(text)
    except json.JSONDecodeError as exc:
        return [], f"{path} is not valid JSON (line {exc.lineno}, column {exc.colno})"
    root = next(
        (n for n in doc.get("@graph", []) if isinstance(n, dict) and n.get("@id") == "./"), None
    )
    if root is None:
        return [], f"{path} has no root dataset"
    item_id = root.get("identifier")
    return [{"id": str(item_id) if item_id else None, "title": root.get("name") or ""}], None


def _csv_items(archive: zipfile.ZipFile) -> tuple[list[dict[str, Any]], str | None]:
    names = sorted(
        n for n in archive.namelist() if "/" in n and n.split("/")[1].endswith((".csv", ".tsv"))
    )
    raw = archive.read(names[0])
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return [], f"{names[0]} is not UTF-8"
    delimiter = "\t" if names[0].endswith(".tsv") else ","
    rows = list(csv.reader(io.StringIO(text), delimiter=delimiter))
    if len(rows) < 2:
        return [], "no header in the import file"
    keys = rows[1]
    items = []
    for row in rows[5:]:
        if not any(row):
            continue
        record = dict(zip(keys, row, strict=False))
        items.append(
            {
                "id": record.get(".id") or None,
                "title": record.get(".metadata.title", ""),
            }
        )
    return items, None


def _xml_items(archive: zipfile.ZipFile) -> tuple[list[dict[str, Any]], str | None]:
    name = next(n for n in archive.namelist() if "/" in n and n.split("/")[1].endswith(".xml"))
    text = archive.read(name).decode("utf-8", "replace")
    match = re.search(r"<dc:title[^>]*>([^<]*)</dc:title>", text)
    if match is None:
        return [], f"{name} has no dc:title"
    return [{"id": None, "title": match.group(1)}], None


# ---------------------------------------------------------------------------
# Request processing
# ---------------------------------------------------------------------------


class Request:
    def __init__(
        self,
        method: str,
        path: str,
        query: str,
        headers: dict[str, str],
        body: bytes,
        base_url: str,
        body_skipped: bool = False,
    ):
        self.method, self.path, self.query = method, path, query
        self.headers = headers  # keys lower-cased
        self.body, self.base_url, self.body_skipped = body, base_url, body_skipped
        self.token: dict[str, Any] | None = None

    def header(self, name: str) -> str | None:
        return self.headers.get(name.lower())

    @property
    def parts(self) -> list[Part]:
        return parse_multipart(self.header("content-type") or "", self.body)


class Response:
    def __init__(
        self,
        status: int,
        body: Any = None,
        headers: dict[str, str] | None = None,
        raw: bytes | None = None,
        content_type: str = "application/json",
    ):
        self.status, self.body, self.headers = status, body, headers or {}
        self.raw, self.content_type = raw, content_type


def normalise_endpoint(method: str, path: str) -> str:
    return f"{method} " + re.sub(r"^/sword/deposit/[^/]+$", "/sword/deposit/{recid}", path)


class Rig:
    """The SWORD behaviour on top of a World."""

    def __init__(self, world: World) -> None:
        self.w = world

    # -- error documents --
    def error_response(self, req: Request, err: SwordError | PlainError | Fault) -> Response:
        w = self.w
        endpoint = f"{req.method} {req.path}"
        if isinstance(err, PlainError):
            if err.status == 401:
                type_, message = "AuthenticationRequired", "Authentication is required."
            else:
                type_, message = "Forbidden", "Not allowed operation in your role or token scope."
            w.log("ERROR", f"{message} ({endpoint} -> {err.status})")
            return Response(err.status, self._error_doc(type_, message))
        if isinstance(err, Fault):
            code = err.code
            sw = SwordError(code, recid=req.path.rsplit("/", 1)[-1])
        else:
            sw = err
        text = f"[{sw.code}] {endpoint}: {sw.message}"
        if sw.status >= 500:
            w.log("ERROR", text + "\n" + _fake_traceback(sw, isinstance(err, Fault)))
        else:
            if sw.log and w.settings.get("faithful_log", True):
                w.log("ERROR", sw.log)
            w.log("WARNING", text)
        return Response(
            sw.status, self._error_doc(sw.type, f"{errtable.PREFIX}{sw.code}: {sw.message}")
        )

    @staticmethod
    def _error_doc(type_: str, error: str) -> dict[str, Any]:
        return {
            "@context": errtable.JSON_LD_CONTEXT,
            "@type": type_,
            "timestamp": utc_now().strftime("%Y-%m-%dT%H:%M:%SZ"),
            "error": error,
        }

    # -- stages --
    def maybe_fault(self, req: Request, stage: str) -> None:
        w = self.w
        endpoint = normalise_endpoint(req.method, req.path)
        with w.lock:
            for fault in list(w.faults):
                target = fault.get("endpoint", "*")
                if target not in ("*", endpoint, endpoint.split(" ", 1)[1], req.method):
                    continue
                code = str(fault["code"])
                default_stage = "auth" if code in ("3108", "3109", "3110") else "process"
                if fault.get("stage", default_stage) != stage:
                    continue
                if fault.get("count", 1) > 0:
                    fault["count"] -= 1
                    if fault["count"] == 0:
                        w.faults.remove(fault)
                raise Fault(code, "fault")

    def container_effects(self, req: Request, stage: str) -> None:
        stopped = self.w.stopped
        if stage == "auth" and "db" in stopped:
            raise Fault("3108", "docker")
        if stage == "process":
            if "redis" in stopped and req.method in ("PUT", "DELETE"):
                raise Fault("3109", "docker")
            if "search" in stopped and req.path.startswith("/sword/deposit/"):
                raise Fault("3110", "docker")

    def authenticate(self, req: Request) -> dict[str, Any]:
        header = req.header("authorization")
        if not header or not header.lower().startswith("bearer "):
            raise PlainError(401)
        value = header.split(None, 1)[1].strip()
        token = self.w.tokens.get(value)
        if token is None or value in self.w.revoked:
            raise PlainError(401)
        req.token = token
        return token

    def check_rate(self) -> None:
        limit = self.w.settings.get("rate_limit")
        if limit:
            self.w.rate_hits += 1
            if self.w.rate_hits > int(limit):
                raise SwordError("2301")

    def require_scopes(self, token: dict[str, Any], *scopes: str) -> None:
        if not set(scopes) <= set(token.get("scopes", [])):
            raise PlainError(403)

    def require_role(self, token: dict[str, Any]) -> None:
        if token.get("role") not in self.w.settings["roles_allowed"]:
            raise PlainError(403)

    def check_on_behalf_of(self, req: Request) -> None:
        if not self.w.settings.get("on_behalf_of") and req.header("on-behalf-of"):
            raise SwordError("1202", log="Not support On-Behalf-Of but request has it.")

    def resolve_obo(self, req: Request) -> None:
        obo = req.header("on-behalf-of")
        if not obo:
            return
        users = self.w.settings.get("obo_users", {})
        if obo not in users:
            raise SwordError("1203")
        if not users[obo]:
            raise SwordError("1204")

    def check_package_contents(self, req: Request) -> Part:
        files = [p for p in req.parts if p.filename is not None]
        if not files or not any(p.name == "file" for p in files):
            raise SwordError("1301", log="No file part.")
        file = next(p for p in files if p.name == "file")
        if file.filename == "":
            raise SwordError("1302", log="No selected file.")
        max_size = int(self.w.settings["max_upload_size"])
        content_length = req.header("content-length")
        if int(content_length or len(file.data)) > max_size:
            raise SwordError(
                "1305",
                log=f"Content size is too large. (request:{content_length}, maxUploadSize:{max_size})",  # noqa: E501
                content_length=content_length,
                max_upload_size=max_size,
            )
        accept = self.w.settings["accept_archive_format"]
        req_ct = (req.header("content-type") or "").split(";")[0] or None
        file_ct = (file.content_type or "").split(";")[0] or None
        failed = None
        if req_ct not in accept:
            failed = req_ct
            if file_ct not in accept:
                failed = file_ct
        if failed is not None:
            raise SwordError(
                "1401", log=f"Not accept Content-Type: {failed}", failed_content_type=failed
            )
        packaging = req.header("packaging")
        accepted_packaging = self.w.settings["accept_packaging"]
        if "*" not in accepted_packaging:
            if packaging not in accepted_packaging:
                raise SwordError(
                    "1402", log=f"Not accept packaging: {packaging}", packaging=packaging
                )
        elif packaging is None:
            raise SwordError(
                "1403", log="Packaging is required, but not contained in request headers."
            )
        return file

    # -- deposit helpers --
    def status_document(self, req: Request, recid: str) -> dict[str, Any]:
        rec = self.w.records.get(recid)
        if rec is None:
            raise SwordError("2101", log=f"Item not found. (recid={recid})", recid=recid)
        url = f"{req.base_url}/sword/deposit/{recid}"
        return {
            "@context": errtable.JSON_LD_CONTEXT,
            "@id": url,
            "@type": "Status",
            "service": f"{req.base_url}/sword/service-document",
            "state": [
                {
                    "@id": "http://purl.org/net/sword/3.0/state/accepted",
                    "description": "The item is held by the stub.",
                }
            ],
            "links": [
                {
                    "@id": url,
                    "rel": ["http://purl.org/net/sword/3.0/terms/statusDocument"],
                    "contentType": "application/json",
                    "status": "http://purl.org/net/sword/3.0/filestate/ingested",
                }
            ],
            "metadata": {"@context": errtable.JSON_LD_CONTEXT, "dc:title": rec["title"]},
        }

    def _client_for(self, req: Request) -> dict[str, Any] | None:
        client = (req.token or {}).get("client")
        return self.w.clients.get(client) if client else None

    def inspect(
        self, req: Request, file: Part, recid: str | None
    ) -> tuple[dict[str, Any] | None, str, list[dict[str, Any]], dict[str, Any]]:
        """Filename, packaging, OBO, digest, format, client, workflow scope, item check.

        Returns (client, format, items, ...) for the caller; raises SwordError.
        """
        disposition = req.header("content-disposition") or ""
        kind, _, rest = disposition.partition(";")
        filename = _disp_param(rest, "filename") if rest else None
        if kind.strip().lower() != "attachment" or filename is None:
            raise SwordError("1303", log="Cannot get filename by Content-Disposition.")
        match = next((p for p in req.parts if p.filename == filename), None)
        if match is None:
            raise SwordError(
                "1304", log=f"Not found {filename} in request body.", filename=filename
            )
        file = match
        packaging = req.header("packaging") or ""
        try:
            archive = zipfile.ZipFile(io.BytesIO(file.data))
        except zipfile.BadZipFile as exc:
            raise RuntimeError(f"File is not a zip file: {exc}") from exc
        with archive:
            fmt = detect_format(archive, packaging)
            self.resolve_obo(req)
            if self.w.settings["digest_verification"]:
                digest = req.header("digest")
                if (
                    not isinstance(digest, str)
                    or not digest.startswith("SHA-256=")
                    or digest.split("SHA-256=")[-1] != _sha256(file.data)
                ):
                    raise SwordError("1306", log="Failed to verify request body and digest.")
            client = self._client_for(req)
            if not self.w.settings["import_enabled"].get(fmt, True):
                raise SwordError("1409", file_format=fmt)
            if fmt == "XML" and client is not None and client.get("register_type") == "Direct":
                raise SwordError("1410")
            if client is None:
                raise SwordError("2103", log="No SWORD API setting found for client.")
            register_type = client.get("register_type", "Direct")
            if register_type == "Workflow":
                if client.get("workflow") == "missing":
                    raise SwordError("2104")
                if client.get("workflow") == "not_registration":
                    raise SwordError("2105")
                assert req.token is not None
                if SCOPE_ACTIVITY not in req.token.get("scopes", []):
                    raise SwordError("1201", log="Required scopes for activity are not satisfied.")
            if fmt == "JSON":
                items, detail = _json_items(archive, packaging)
            elif fmt == "XML":
                items, detail = _xml_items(archive)
            else:
                items, detail = _csv_items(archive)
        if detail:
            raise SwordError("1501", log=f"Error in check_import_items: {detail}", detail=detail)
        for item in items:
            if not item["title"]:
                detail = "title is required"
                raise SwordError(
                    "1501", log=f"Error in check_import_items: {detail}", detail=detail
                )
            if item["id"] is None:
                item["status"] = "new"
            elif item["id"] in self.w.records:
                item["status"] = "exists"
            else:
                detail = f"item {item['id']} does not exist"
                raise SwordError(
                    "1501", log=f"Error in check_import_items: {detail}", detail=detail
                )
        if not items:
            raise SwordError(
                "1501", log="Error in check_import_items: item_missing", detail="item_missing"
            )
        return client, fmt, items, {}

    def is_duplicate(self, title: str, exclude: str | None = None) -> bool:
        return any(rec["title"] == title for rid, rec in self.w.records.items() if rid != exclude)

    def lock_item(self, recid: str) -> None:
        rec = self.w.records[recid]
        now = time.monotonic()
        if rec["locked"] or rec["locked_until"] > now or self._redis_locked(recid):
            raise SwordError(
                "2201", log=f"Item {recid} will be edited by another process.", recid=recid
            )
        rec["locked_until"] = now + float(self.w.settings.get("lock_seconds", 0))

    def _redis_locked(self, recid: str) -> bool:
        now = time.time()
        for key, (_value, expiry) in self.w.redis.items():
            if expiry is not None and expiry < now:
                continue
            m = re.search(r"lock.*?(\d+)$", key)
            if m and m.group(1) == recid:
                return True
        return False

    # -- endpoints --
    def service_document(self, req: Request) -> Response:
        self.maybe_fault(req, "auth")
        self.container_effects(req, "auth")
        self.authenticate(req)
        self.check_rate()
        self.check_on_behalf_of(req)
        self.maybe_fault(req, "process")
        s = self.w.settings
        doc = {
            "@context": errtable.JSON_LD_CONTEXT,
            "@type": "ServiceDocument",
            "@id": f"{req.base_url}/sword/service-document",
            "root": f"{req.base_url}/sword/service-document",
            "dc:title": "sword-stub (mechanics rig, not WEKO)",
            "version": "http://purl.org/net/sword/3.0",
            "acceptArchiveFormat": s["accept_archive_format"],
            "acceptPackaging": s["accept_packaging"],
            "maxUploadSize": s["max_upload_size"],
            "onBehalfOf": bool(s["on_behalf_of"]),
        }
        self.w.log("INFO", "GET /sword/service-document -> 200")
        return Response(200, doc)

    def post_service_document(self, req: Request) -> Response:
        self.maybe_fault(req, "auth")
        self.container_effects(req, "auth")
        token = self.authenticate(req)
        self.check_rate()
        self.require_scopes(token, SCOPE_WRITE, SCOPE_ACTIONS)
        self.require_scopes(token, SCOPE_CREATE)
        self.require_role(token)
        self.check_on_behalf_of(req)
        if req.body_skipped:
            raise SwordError(
                "1305",
                content_length=req.header("content-length"),
                max_upload_size=self.w.settings["max_upload_size"],
            )
        file = self.check_package_contents(req)
        client, _fmt, items, _ = self.inspect(req, file, None)
        register_type = client.get("register_type", "Direct")
        if register_type not in ("Direct", "Workflow"):
            raise RuntimeError(f"unknown registration type {register_type!r}")
        for item in items:
            if item["status"] != "new":
                raise SwordError(
                    "1502", log="This item is already registered.", item_title=item["title"]
                )
            if client.get("duplicate_check") and self.is_duplicate(item["title"]):
                raise SwordError("1503", log="New item appears to be a duplicate.", list_url="")
        self.maybe_fault(req, "process")
        self.container_effects(req, "process")
        recids = []
        with self.w.lock:
            for item in items:
                recid = self.w.allocate_recid()
                self.w.records[recid] = self.w._new_record({"title": item["title"]})
                recids.append(recid)
        self.w.db_log.append(
            f"{iso(utc_now())} LOG:  statement: INSERT INTO records_metadata ({', '.join(recids)})"
        )
        self.w.log(
            "INFO",
            f"Items imported via SWORD api by {client.get('name', 'client')} (recid={recids[-1]})",
        )
        status = (
            202 if register_type == "Workflow" and client.get("action") != "end_action" else 201
        )
        doc = self.status_document(req, recids[0])
        headers = {}
        if self.w.settings.get("location_header", True):
            headers["Location"] = f"{req.base_url}/sword/deposit/{recids[0]}"
        if len(recids) > 1:
            doc = {
                "@context": errtable.JSON_LD_CONTEXT,
                "@type": "StatusList",
                "items": [self.status_document(req, r) for r in recids],
            }
        return Response(status, doc, headers)

    def get_deposit(self, req: Request, recid: str) -> Response:
        self.maybe_fault(req, "auth")
        self.container_effects(req, "auth")
        self.authenticate(req)
        self.check_on_behalf_of(req)
        self.maybe_fault(req, "process")
        self.container_effects(req, "process")
        if any(f["kind"] == "corrupt_record_json" for f in self.w.helper_faults):
            raise RuntimeError("record JSON is corrupt (injected by helper fault)")
        doc = self.status_document(req, recid)
        self.w.log("INFO", f"GET /sword/deposit/{recid} -> 200")
        return Response(200, doc)

    def put_deposit(self, req: Request, recid: str) -> Response:
        self.maybe_fault(req, "auth")
        self.container_effects(req, "auth")
        token = self.authenticate(req)
        self.check_rate()
        self.require_scopes(token, SCOPE_WRITE, SCOPE_ACTIONS)
        self.require_scopes(token, SCOPE_UPDATE)
        self.require_role(token)
        self.check_on_behalf_of(req)
        if req.body_skipped:
            raise SwordError(
                "1305",
                content_length=req.header("content-length"),
                max_upload_size=self.w.settings["max_upload_size"],
            )
        file = self.check_package_contents(req)
        self.status_document(req, recid)  # 2101
        client, _fmt, items, _ = self.inspect(req, file, recid)
        register_type = client.get("register_type", "Direct")
        if len(items) > 1:
            raise SwordError("1504", log="Multiple items found in import file.")
        item = items[0]
        if item["status"] == "new":
            raise SwordError(
                "1505", log="This item is not registered yet.", item_title=item["title"]
            )
        if item["id"] != recid:
            raise SwordError("1506", log="Item id does not match.", item_id=item["id"], recid=recid)
        if client.get("duplicate_check") and self.is_duplicate(item["title"], exclude=recid):
            raise SwordError("1503", log="New item appears to be a duplicate.", list_url="")
        if register_type not in ("Direct", "Workflow"):
            raise SwordError("3103")
        self.maybe_fault(req, "process")
        self.container_effects(req, "process")
        if any(
            f["kind"] in ("trigger_raise", "check_violation_new_rows") for f in self.w.helper_faults
        ):
            raise SwordError(
                "3105", log="Failed to update item (injected helper fault).", recid=recid
            )
        if register_type == "Direct":
            self.lock_item(recid)
        rec = self.w.records[recid]
        rec["title"], rec["version"] = item["title"], rec["version"] + 1
        self.w.db_log.append(
            f"{iso(utc_now())} LOG:  statement: UPDATE records_metadata WHERE recid={recid}"
        )
        self.w.log(
            "INFO", f"Item updated via SWORD api by {client.get('name', 'client')} (recid={recid})"
        )
        status = (
            202 if register_type == "Workflow" and client.get("action") != "end_action" else 200
        )
        return Response(status, self.status_document(req, recid))

    def delete_deposit(self, req: Request, recid: str) -> Response:
        self.maybe_fault(req, "auth")
        self.container_effects(req, "auth")
        token = self.authenticate(req)
        self.check_rate()
        self.require_scopes(token, SCOPE_WRITE, SCOPE_ACTIONS)
        self.require_scopes(token, SCOPE_DELETE)
        self.require_role(token)
        self.check_on_behalf_of(req)
        self.status_document(req, recid)  # 2101
        rec = self.w.records[recid]
        if rec["doi"]:
            raise SwordError("2106", log=f"Cannot delete item with DOI; item id {recid}")
        self.resolve_obo(req)
        client = self._client_for(req)
        if client is None:
            raise SwordError("2103", log="No SWORD API setting found for client.")
        register_type = client.get("register_type", "Direct")
        if register_type not in ("Direct", "Workflow"):
            raise SwordError("3102", register_type=register_type)
        if register_type == "Workflow" and SCOPE_ACTIVITY not in token.get("scopes", []):
            raise SwordError("1201", log="Required scopes for activity are not satisfied.")
        self.maybe_fault(req, "process")
        self.container_effects(req, "process")
        if register_type == "Direct":
            self.lock_item(recid)
        if rec["importing"]:
            raise SwordError("2202")
        if rec["editing"]:
            raise SwordError("2203")
        if any(
            f["kind"] in ("trigger_raise", "check_violation_new_rows") for f in self.w.helper_faults
        ):
            raise SwordError(
                "3106", log="Failed to delete item (injected helper fault).", recid=recid
            )
        with self.w.lock:
            del self.w.records[recid]
            self.w.deleted.append(recid)
        self.w.db_log.append(
            f"{iso(utc_now())} LOG:  statement: DELETE FROM records_metadata WHERE recid={recid}"
        )
        self.w.log(
            "INFO", f"Item deleted by sword from {client.get('name', 'client')} (recid={recid})"
        )
        status = (
            202 if register_type == "Workflow" and client.get("deletion") == "approval" else 204
        )
        return Response(status, None)

    # -- dispatch --
    def handle(self, req: Request) -> Response:
        method, path = req.method, req.path
        try:
            try:
                m = re.fullmatch(r"/sword/deposit/([^/]+)", path)
                if path == "/sword/service-document" and method == "GET":
                    return self.service_document(req)
                if path == "/sword/service-document" and method == "POST":
                    return self.post_service_document(req)
                if m and method == "GET":
                    return self.get_deposit(req, m.group(1))
                if m and method == "PUT":
                    return self.put_deposit(req, m.group(1))
                if m and method == "DELETE":
                    return self.delete_deposit(req, m.group(1))
                if path == "/sword/service-document" or m:
                    return self._plain(405, "MethodNotAllowed", "Method not allowed.")
                return self._plain(404, "NotFound", "Not found.")
            except (SwordError, PlainError, Fault) as err:
                return self.error_response(req, err)
        except DropConnection:
            raise
        except Exception as exc:  # the blueprint's catch-all handler: 3201
            self.w.log("ERROR", f"{exc}\n{traceback.format_exc().rstrip()}")
            sw = SwordError("3201")
            return Response(
                sw.status, self._error_doc(sw.type, f"{errtable.PREFIX}3201: {sw.message}")
            )

    def _plain(self, status: int, type_: str, message: str) -> Response:
        self.w.log("WARNING", f"{status} {message}")
        return Response(status, self._error_doc(type_, message))


def _fake_traceback(err: SwordError, injected: bool) -> str:
    origin = "injected fault" if injected else "stub code path"
    return (
        "Traceback (most recent call last):\n"
        '  File "/code/weko-swordserver/weko_swordserver/views.py", line 0, in handler\n'
        f"    raise {errtable.msgid(err.code)}()  # fake traceback ({origin})\n"
        f"weko_swordserver.errors.WekoSwordserverException: {err.message}"
    )


# ---------------------------------------------------------------------------
# Control endpoints, helper emulation and the admin screen
# ---------------------------------------------------------------------------


def _helper_ok(result: Any) -> dict[str, Any]:
    return {"ok": True, "result": result}


def _helper_fail(type_: str, message: str) -> dict[str, Any]:
    return {"ok": False, "error": {"type": type_, "message": message}}


HELPER_COMMANDS = [
    "create_record",
    "delete_record",
    "create_token",
    "create_user",
    "inject_fault",
    "insert_doi_pid",
    "list_faults",
    "orphan_record",
    "ping",
    "register_sword_client",
    "restore_fault",
    "revoke_token",
    "set_client_field",
    "snapshot",
]


def run_helper(world: World, cmd: str, params: dict[str, Any]) -> dict[str, Any]:
    """The in-container helper contract (helpers/run.py) against the stub's state."""
    w = world
    with w.lock:
        if cmd == "list":
            return _helper_ok(sorted(HELPER_COMMANDS + ["list"]))
        if cmd == "ping":
            return _helper_ok(
                {"db_ok": True, "db_version": "stub", "packages": {}, "commit": "stub"}
            )
        if cmd == "create_user":
            email = params.get("email")
            if not isinstance(email, str) or "@" not in email:
                return _helper_fail("InvalidArgument", "email must be a non-empty string")
            previous = w.users.get(email)
            roles = list(params.get("roles") or [])
            w.users[email] = {"roles": sorted(set(roles) | set((previous or {}).get("roles", [])))}
            return _helper_ok(
                {
                    "id": len(w.users),
                    "created": previous is None,
                    "roles_added": [r for r in roles if r not in (previous or {}).get("roles", [])],
                    "previous": previous,
                }
            )
        if cmd == "create_token":
            email = params.get("user_email")
            name = params.get("name")
            if not isinstance(name, str) or not name:
                return _helper_fail("InvalidArgument", "name must be a non-empty string")
            user = w.users.get(email or "", {"roles": []})
            prefix = params.get("token_prefix", "WEKO_TEST_TOKEN_")
            existing = next((t for t, v in w.tokens.items() if v.get("name") == name), None)
            scopes = list(params.get("scopes") or [])
            if existing:
                previous_scopes = w.tokens[existing].get("scopes", [])
                w.tokens[existing]["scopes"] = scopes
                return _helper_ok(
                    {
                        "access_token": existing,
                        "token_id": 1,
                        "client_id": w.tokens[existing].get("client"),
                        "scopes": scopes,
                        "reused": True,
                        "previous_scopes": previous_scopes,
                    }
                )
            w.minted += 1
            token = f"{prefix}{uuid.uuid4().hex}"
            client_name = params.get("client_name") or name
            roles = user.get("roles") or []
            w.tokens[token] = {
                "name": name,
                "scopes": scopes,
                "client": client_name,
                "role": roles[0] if roles else None,
            }
            return _helper_ok(
                {
                    "access_token": token,
                    "token_id": w.minted,
                    "client_id": client_name,
                    "scopes": scopes,
                    "reused": False,
                    "previous_scopes": None,
                }
            )
        if cmd == "revoke_token":
            target = params.get("access_token") or next(
                (t for t, v in w.tokens.items() if v.get("name") == params.get("name")), None
            )
            if target and target in w.tokens:
                del w.tokens[target]
                return _helper_ok({"deleted_tokens": [1], "deleted_clients": []})
            return _helper_ok({"deleted_tokens": [], "deleted_clients": []})
        if cmd == "register_sword_client":
            cid = params.get("client_id") or params.get("client_name")
            if not cid:
                return _helper_fail("InvalidArgument", "client_id or client_name is required")
            reg = params.get("registration_type", "Direct")
            previous = w.clients.get(cid)
            w.clients[cid] = {
                **(previous or {}),
                "name": cid,
                "register_type": reg,
                "duplicate_check": bool(params.get("duplicate_check", False)),
                "workflow_id": params.get("workflow_id"),
            }
            return _helper_ok(
                {
                    "created": previous is None,
                    "current": w.clients[cid],
                    "previous": previous,
                    "previous_delete_flow": None,
                }
            )
        if cmd == "set_client_field":
            cid, field, value = params.get("client_id"), params.get("field"), params.get("value")
            if cid not in w.clients:
                return _helper_fail("NotFound", f"client {cid} not found")
            key = (
                "register_type" if field in ("registration_type", "registration_type_id") else field
            )
            if key == "register_type" and value in (1, "1"):
                value = "Direct"
            elif key == "register_type" and value in (2, "2"):
                value = "Workflow"
            previous = w.clients[cid].get(key)
            w.clients[cid][key] = value
            return _helper_ok({"previous": previous, "value": value})
        if cmd == "create_record":
            title = params.get("title")
            if not isinstance(title, str) or not title:
                return _helper_fail("InvalidArgument", "title must be a non-empty string")
            recid = str(params["recid"]) if params.get("recid") else w.allocate_recid()
            created = recid not in w.records
            if created:
                w.records[recid] = w._new_record(
                    {"title": title, "doi": bool(params.get("with_doi"))}
                )
                w.deleted = [d for d in w.deleted if d != recid]
            doi = f"https://doi.org/ath-test/{recid}" if w.records[recid]["doi"] else None
            return _helper_ok(
                {
                    "recid": recid,
                    "uuid": str(uuid.uuid5(uuid.NAMESPACE_URL, recid)),
                    "created": created,
                    "doi": doi,
                }
            )
        if cmd == "delete_record":
            # Idempotent like the real helper; reports the state it found.
            recid = str(params.get("recid"))
            if params.get("restore"):
                restored = recid in w.deleted
                w.deleted = [d for d in w.deleted if d != recid]
                if restored:
                    w.records.setdefault(recid, w._new_record({"title": "restored"}))
                return _helper_ok({"recid": recid, "restored": restored})
            previous = (
                "deleted" if recid in w.deleted else "registered" if recid in w.records else None
            )
            if recid in w.records:
                del w.records[recid]
                w.deleted.append(recid)
            return _helper_ok(
                {"recid": recid, "previous": previous, "deleted": previous is not None}
            )
        if cmd == "insert_doi_pid":
            recid = str(params.get("recid"))
            if recid not in w.records:
                return _helper_fail("NotFound", f"record {recid} not found")
            created = not w.records[recid]["doi"]
            w.records[recid]["doi"] = True
            return _helper_ok(
                {
                    "doi": params.get("doi") or f"https://doi.org/ath-test/{recid}",
                    "created": created,
                }
            )
        if cmd == "orphan_record":
            recid = str(params.get("recid"))
            if params.get("restore"):
                w.records.setdefault(recid, w._new_record(params["restore"]))
                return _helper_ok({"restored_tables": ["records_metadata"]})
            rec = w.records.pop(recid, None)
            return _helper_ok({"backup": rec})
        if cmd == "snapshot":
            return _helper_ok(_snapshot(w, params))
        if cmd == "inject_fault":
            kind = params.get("kind")
            if not isinstance(kind, str):
                return _helper_fail("InvalidArgument", "kind must be a string")
            fault = {
                "kind": kind,
                "fault_id": len(w.helper_faults) + 1,
                "params": params.get("params") or {},
            }
            w.helper_faults.append(fault)
            return _helper_ok({"fault_id": fault["fault_id"], "info": {"stub": True}})
        if cmd == "restore_fault":
            kind = params.get("kind", "all")
            kept = [] if kind == "all" else [f for f in w.helper_faults if f["kind"] != kind]
            restored = [f["fault_id"] for f in w.helper_faults if f not in kept]
            w.helper_faults = kept
            return _helper_ok({"restored": restored, "swept": [], "warnings": []})
        if cmd == "list_faults":
            return _helper_ok(copy.deepcopy(w.helper_faults))
    return _helper_fail("UnknownCommand", f"unknown command: {cmd}")


def _snapshot(w: World, params: dict[str, Any]) -> dict[str, Any]:
    def digest(obj: Any) -> str:
        return _sha256(json.dumps(obj, sort_keys=True).encode())

    tables = params.get("tables") or ["records", "tokens", "sword_clients"]
    out: dict[str, Any] = {}
    recid = params.get("recid")
    for table in tables:
        if table == "records":
            rows = {r: digest(v) for r, v in w.records.items() if recid in (None, r)}
        elif table == "tokens":  # never the token value
            rows = {
                v.get("name", "?"): digest({**v, "revoked": t in w.revoked})
                for t, v in w.tokens.items()
            }
        elif table == "sword_clients":
            rows = {c: digest(v) for c, v in w.clients.items()}
        else:
            rows = {}
        out[table] = {"count": len(rows), "rows": rows}
    return out


def handle_control(world: World, req: Request) -> Response:
    sub = req.path[len(CONTROL_PREFIX) :]
    w = world
    try:
        payload = json.loads(req.body.decode("utf-8")) if req.body else {}
    except ValueError:
        return Response(400, {"error": "body is not JSON"})
    if sub == "state" and req.method == "GET":
        return Response(200, w.state())
    if sub == "reset" and req.method == "POST":
        w.reset(clear_log=bool(payload.get("clear_log", False)))
        w.log("INFO", "stub reset")
        return Response(200, {"ok": True})
    if sub == "fault" and req.method == "POST":
        if str(payload.get("code")) not in errtable.SPECS:
            return Response(400, {"error": f"unknown error code {payload.get('code')!r}"})
        fault = {
            "endpoint": payload.get("endpoint", "*"),
            "code": str(payload["code"]),
            "count": int(payload.get("count", 1)),
        }
        if "stage" in payload:
            fault["stage"] = payload["stage"]
        with w.lock:
            w.faults.append(fault)
        return Response(200, {"ok": True, "fault": fault})
    if sub == "fault" and req.method == "DELETE":
        with w.lock:
            w.faults.clear()
        return Response(200, {"ok": True})
    if sub == "helper" and req.method == "POST":
        return Response(
            200, run_helper(w, str(payload.get("cmd", "")), payload.get("params") or {})
        )
    if sub == "docker" and req.method == "POST":
        return Response(200, docker_action(w, payload))
    if sub == "logs" and req.method == "GET":
        query = urllib.parse.parse_qs(req.query)
        container = (query.get("container") or [""])[0]
        since = (query.get("since") or [None])[0]
        role = w.role_of_container(container)
        lines = w.db_log if role == "db" else w.log_since(since) if role in (None, "web") else []
        if role == "db" and since:
            floor = _parse_ts(since)
            lines = [
                x
                for x in lines
                if floor is None or (_parse_ts(x.split(" ", 1)[0]) or floor) >= floor
            ]
        return Response(
            200,
            None,
            raw=("\n".join(lines) + ("\n" if lines else "")).encode(),
            content_type="text/plain; charset=utf-8",
        )
    return Response(404, {"error": f"no control endpoint {req.method} {req.path}"})


def docker_action(w: World, payload: dict[str, Any]) -> dict[str, Any]:
    action, container = payload.get("action"), payload.get("container", "")
    role = w.role_of_container(container)
    if role is None:
        return {
            "ok": False,
            "stderr": f"Error response from daemon: No such container: {container}\n",
            "exit": 1,
        }
    with w.lock:
        if action == "stop":
            w.stopped.add(role)
        elif action == "start" or action == "restart":
            w.stopped.discard(role)
        elif action == "redis":
            return _redis(w, payload.get("args", []))
        else:
            return {"ok": False, "stderr": f"unsupported docker action {action!r}\n", "exit": 1}
    w.log("INFO", f"container {container} {action}")
    return {"ok": True, "stdout": container + "\n", "exit": 0}


def _redis(w: World, args: list[str]) -> dict[str, Any]:
    """A few single-key redis-cli commands (the DB number is ignored)."""
    now = time.time()
    for key in [k for k, (_v, e) in w.redis.items() if e is not None and e < now]:
        del w.redis[key]
    if not args:
        return {"ok": False, "stderr": "ERR wrong number of arguments\n", "exit": 1}
    cmd, rest = args[0].upper(), args[1:]
    if cmd == "SETEX" and len(rest) == 3:
        w.redis[rest[0]] = (rest[2], now + float(rest[1]))
        return {"ok": True, "stdout": "OK\n", "exit": 0}
    if cmd == "GET" and rest:
        value = w.redis.get(rest[0])
        return {"ok": True, "stdout": (value[0] if value else "") + "\n", "exit": 0}
    if cmd == "EXISTS" and rest:
        return {"ok": True, "stdout": f"{int(rest[0] in w.redis)}\n", "exit": 0}
    if cmd == "DEL" and rest:
        return {"ok": True, "stdout": f"{int(w.redis.pop(rest[0], None) is not None)}\n", "exit": 0}
    if cmd == "TTL" and rest:
        entry = w.redis.get(rest[0])
        ttl = -2 if entry is None else -1 if entry[1] is None else int(entry[1] - now)
        return {"ok": True, "stdout": f"{ttl}\n", "exit": 0}
    return {"ok": False, "stderr": f"ERR unknown command '{cmd}'\n", "exit": 1}


# -- admin screen --

ADMIN_CSS = """body{font-family:sans-serif;margin:2rem;max-width:42rem}
.banner{background:#fde68a;border:1px solid #b45309;padding:.5rem;margin-bottom:1rem}
table{border-collapse:collapse}td,th{border:1px solid #888;padding:.25rem .5rem}
"""
ADMIN_BANNER = (
    '<div class="banner" data-testid="stub-banner">sword-stub: mechanics rig. '
    "This is NOT WEKO and proves nothing about WEKO's behaviour.</div>"
)


def _page(title: str, body: str, script: str = "") -> bytes:
    return (
        f'<!doctype html><html lang="en"><head><meta charset="utf-8"><title>{title}</title>'
        f"<style>{ADMIN_CSS}</style></head><body>{ADMIN_BANNER}{body}"
        f"<script>{script}</script></body></html>"
    ).encode()


def login_page(error: str = "") -> bytes:
    note = f'<p data-testid="login-error" role="alert">{error}</p>' if error else ""
    return _page(
        "stub admin login",
        '<h1 data-testid="page-title">Stub admin login</h1>'
        + note
        + '<form method="post" action="/stub-admin/login" data-testid="login-form">'
        '<label>User <input name="user" data-testid="login-user"></label> '
        '<label>Password <input name="password" type="password" data-testid="login-password"></label> '  # noqa: E501
        '<button type="submit" data-testid="login-submit">Sign in</button></form>',
    )


def dashboard_page(w: World) -> bytes:
    rows = []
    with w.lock:
        for token, info in w.tokens.items():
            name = info.get("name", "?")
            revoked = token in w.revoked
            rows.append(
                f'<tr data-testid="row-{name}"><td>{name}</td><td>{info.get("client", "")}</td>'
                f'<td data-testid="status-{name}">{"revoked" if revoked else "active"}</td>'
                f'<td><button data-testid="revoke-{name}" data-name="{name}" class="revoke">Revoke</button></td></tr>'  # noqa: E501
            )
    script = """
document.querySelectorAll('.revoke').forEach(function (b) {
  b.addEventListener('click', async function () {
    var name = b.dataset.name;
    var r = await fetch('/stub-admin/revoke', {
      method: 'POST', headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({name: name})});
    var j = await r.json();
    var cell = document.querySelector("[data-testid='status-" + name + "']");
    cell.textContent = j.revoked ? 'revoked' : 'unknown';
    document.querySelector("[data-testid='message']").textContent = 'revoked ' + name;
  });
});
document.querySelector("[data-testid='log-console-error']").addEventListener('click', function () {
  console.error('stub-admin: intentional console error');
  document.querySelector("[data-testid='message']").textContent = 'console error logged';
});
"""
    body = (
        '<h1 data-testid="page-title">Stub admin</h1><p data-testid="message">ready</p>'
        '<table data-testid="token-table"><tr><th>Token</th><th>Client</th><th>State</th><th></th></tr>'  # noqa: E501
        + "".join(rows)
        + '</table><p><button data-testid="log-console-error">Log a console error</button></p>'
    )
    return _page("stub admin", body, script)


# ---------------------------------------------------------------------------
# HTTP server
# ---------------------------------------------------------------------------


class StubServer(ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True

    def __init__(self, address: tuple[str, int], world: World) -> None:
        super().__init__(address, StubHandler)
        self.world = world
        self.rig = Rig(world)
        self.sessions: set[str] = set()

    def server_bind(self) -> None:
        # HTTPServer.server_bind resolves the host name, which can take seconds
        # without DNS; the rig only needs the bound address.
        import socketserver

        socketserver.TCPServer.server_bind(self)
        self.server_name, self.server_port = self.server_address[0], self.server_address[1]

    @property
    def url(self) -> str:
        host, port = self.server_address[:2]
        return f"http://{host}:{port}"


class StubHandler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"
    server: StubServer
    server_version = "sword-stub"

    def log_message(self, format: str, *args: Any) -> None:  # noqa: A002 - stdlib signature
        pass

    def _read_body(self) -> tuple[bytes, bool]:
        length = int(self.headers.get("Content-Length") or 0)
        if length > MAX_READ_BYTES:
            return b"", True
        return self.rfile.read(length), False

    def _dispatch(self) -> None:
        parsed = urllib.parse.urlsplit(self.path)
        path = urllib.parse.unquote(parsed.path)
        body, skipped = self._read_body()
        headers = {k.lower(): v for k, v in self.headers.items()}
        host = (
            headers.get("host")
            or f"{self.server.server_address[0]}:{self.server.server_address[1]}"
        )
        req = Request(self.command, path, parsed.query, headers, body, f"http://{host}", skipped)
        w = self.server.world
        try:
            if path.startswith(CONTROL_PREFIX):
                resp = handle_control(w, req)
            else:
                if "web" in w.stopped:
                    raise DropConnection
                if path.startswith(ADMIN_PREFIX):
                    resp = self._admin(req)
                else:
                    resp = self.server.rig.handle(req)
                    if resp.status < 400:
                        w.log("INFO", f"{self.command} {path} -> {resp.status}")
        except DropConnection:
            self.close_connection = True
            self.connection.close()
            return
        self._send(resp, close=skipped)

    def _admin(self, req: Request) -> Response:
        w, srv = self.server.world, self.server
        cookie = req.header("cookie") or ""
        session = re.search(r"stub_session=([0-9a-f]+)", cookie)
        authed = bool(session and session.group(1) in srv.sessions)
        sub = req.path[len(ADMIN_PREFIX) :] or "/"
        html = "text/html; charset=utf-8"
        if sub == "/" and req.method == "GET":
            page = dashboard_page(w) if authed else login_page()
            return Response(200, None, raw=page, content_type=html)
        if sub == "/login" and req.method == "POST":
            form = urllib.parse.parse_qs(req.body.decode("utf-8", "replace"))
            ok = (
                form.get("user", [""])[0] == w.admin["user"]
                and form.get("password", [""])[0] == w.admin["password"]
            )
            if not ok:
                w.log("WARNING", "admin login failed")
                return Response(401, None, raw=login_page("Invalid credentials"), content_type=html)
            sid = uuid.uuid4().hex
            srv.sessions.add(sid)
            w.log("INFO", "admin login ok")
            return Response(
                303,
                None,
                {"Location": "/stub-admin/", "Set-Cookie": f"stub_session={sid}; Path=/; HttpOnly"},
                raw=b"",
            )
        if sub == "/revoke" and req.method == "POST":
            if not authed:
                return Response(401, {"error": "login required"})
            name = json.loads(req.body.decode("utf-8") or "{}").get("name")
            with w.lock:
                hit = [t for t, v in w.tokens.items() if v.get("name") == name]
                w.revoked.update(hit)
            w.log("INFO", f"admin revoked token {name}")
            return Response(200, {"revoked": bool(hit), "name": name})
        return Response(404, None, raw=_page("not found", "<p>not found</p>"), content_type=html)

    def _send(self, resp: Response, close: bool = False) -> None:
        if resp.raw is not None:
            payload = resp.raw
        elif resp.body is None:
            payload = b""
        else:
            payload = json.dumps(resp.body, ensure_ascii=False).encode("utf-8")
        self.send_response(resp.status)
        self.send_header(*STUB_HEADER)
        if payload or resp.status not in (204, 304):
            self.send_header("Content-Type", resp.content_type)
        self.send_header("Content-Length", str(len(payload)))
        for key, value in resp.headers.items():
            self.send_header(key, value)
        if close:
            self.send_header("Connection", "close")
            self.close_connection = True
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(payload)

    do_GET = do_POST = do_PUT = do_DELETE = do_PATCH = do_HEAD = do_OPTIONS = _dispatch


def make_server(
    config: dict[str, Any] | None = None,
    log_file: str | None = None,
    host: str = "127.0.0.1",
    port: int = 0,
) -> StubServer:
    """Builds a server (not yet serving). `port=0` picks a free port."""
    return StubServer((host, port), World(config or {}, log_file))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=BANNER)
    parser.add_argument("--config", help="stub.json describing tokens, clients and records")
    parser.add_argument("--log-file", help="application log (WARNING 4xx, ERROR 5xx)")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8080, help="0 picks a free port")
    parser.add_argument("--port-file", help="write the chosen port here once listening")
    args = parser.parse_args(argv)
    config = json.loads(Path(args.config).read_text(encoding="utf-8")) if args.config else {}
    server = make_server(config, args.log_file, args.host, args.port)
    print(BANNER, file=sys.stderr, flush=True)
    print(f"sword-stub listening on {server.url}", file=sys.stderr, flush=True)
    if args.port_file:
        Path(args.port_file).write_text(str(server.server_address[1]), encoding="utf-8")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
