#!/usr/bin/env bash
# End-to-end proof of the generation pipeline against the SWORD mechanics rig.
#
#   scripts/rig-e2e.sh [--no-browser] [--keep]
#
# The rig (tools/sword-stub) is NOT WEKO. This script only shows that tests
# generated by the hub run mechanically: multipart upload, omitted headers,
# bearer tokens, assertions on error JSON, evidence with masking, helper and
# docker calls (through tools/sword-stub/fake_docker.py), and a browser step.
# It proves nothing about WEKO.
#
# Everything is written under a temporary directory (printed at the end);
# nothing under specs/ or tests/ is touched. fixtures/generated/ (git-ignored)
# is (re)built because the baselines point at it.
#
#   --no-browser   skip the Playwright scenario (CI without Chromium)
#   --unpatched    do not apply the rig-only workaround for docs/stub.md finding F-1
#                  (the hub ignores a case's evidence.ignore); error cases then fail
#   --keep         accepted for compatibility; the directory is always kept and printed
#
# A sandbox Chromium whose revision differs from the one Playwright pins is
# handled by a throwaway PLAYWRIGHT_BROWSERS_PATH of symlinks (never committed).
set -euo pipefail
# shellcheck source=lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
cd "$REPO_ROOT"

BROWSER=1
PATCH_IGNORE=1
for arg in "$@"; do
  case "$arg" in
    --no-browser) BROWSER=0 ;;
    --unpatched) PATCH_IGNORE=0 ;;
    --keep) ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

STUB_DIR="tools/sword-stub"
EXAMPLES="$STUB_DIR/examples"
WORK="${RIG_WORK:-$(mktemp -d "${TMPDIR:-/tmp}/rig-e2e.XXXXXX")}"
EVIDENCE="$WORK/evidence"
step() { printf '\n== %s\n' "$*"; }

if [ ! -f "$HUB_DIR/packages/cli/bin/generate-test.ts" ]; then
  echo "hub not found at $HUB_DIR; run scripts/bootstrap-hub.sh" >&2
  exit 1
fi

step "fixtures"
uv run python seeds/build_fixtures.py build --out fixtures/generated --manifest "$WORK/manifest.json"

step "stub configuration"
# The token is a fixed fake that only exists in the rig's example config and specs.
RIG_TOKEN="STUBTOKEN-direct-admin"
RIG_ADMIN_PASSWORD="rig-pass-$(uv run python -c 'import secrets; print(secrets.token_hex(4))')"
export RIG_TOKEN RIG_ADMIN_PASSWORD
uv run python - "$STUB_DIR/stub.example.json" "$WORK/stub.json" <<'PY'
import json, os, sys
config = json.load(open(sys.argv[1]))
config["admin"] = {"user": "admin", "password": os.environ["RIG_ADMIN_PASSWORD"]}
json.dump(config, open(sys.argv[2], "w"), indent=2)
PY

step "start the stub"
uv run python "$STUB_DIR/stub_server.py" --config "$WORK/stub.json" --port 0 \
  --port-file "$WORK/port" --log-file "$WORK/app.log" 2> "$WORK/stub.stderr" &
STUB_PID=$!
trap 'kill "$STUB_PID" 2>/dev/null || true' EXIT
for _ in $(seq 1 100); do
  [ -s "$WORK/port" ] && break
  sleep 0.1
done
[ -s "$WORK/port" ] || { echo "stub did not start" >&2; cat "$WORK/stub.stderr" >&2; exit 1; }
STUB_URL="http://127.0.0.1:$(cat "$WORK/port")"
cat "$WORK/stub.stderr"

step "fake docker on PATH"
mkdir -p "$WORK/bin"
printf '#!/bin/sh\nexec "%s" "%s" "$@"\n' "$(uv run python -c 'import sys; print(sys.executable)')" \
  "$REPO_ROOT/$STUB_DIR/fake_docker.py" > "$WORK/bin/docker"
chmod +x "$WORK/bin/docker"
export STUB_URL
export PATH="$WORK/bin:$PATH"
export WEKO_BASE_URL="$STUB_URL"
export WEKO_WEB_CONTAINER=weko-web-1 WEKO_DB_CONTAINER=weko-db-1 WEKO_REDIS_CONTAINER=weko-redis-1

step "plugin copy with the rig-only browser operation, specs copy"
uv run python "$EXAMPLES/make_rig_plugin.py" plugin.yaml "$EXAMPLES/rig-ops.yaml" "$WORK/plugin.yaml"
node scripts/validate-plugin.ts "$HUB_DIR" "$WORK/plugin.yaml"
cp -r "$EXAMPLES/specs" "$WORK/specs"
node "$HUB_DIR/scripts/validate-specs.ts" "$WORK/specs"

step "generate Python tests with the hub"
IDS="TC-RIG-001 TC-RIG-401 TC-RIG-1306 SC-RIG-LIFECYCLE"
[ "$BROWSER" = 1 ] && IDS="$IDS TC-RIG-UI"
for id in $IDS; do
  module="$(printf '%s' "$id" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/_/g')"
  node "$HUB_DIR/packages/cli/bin/generate-test.ts" "$id" \
    --specs "$WORK/specs" --plugin "$WORK/plugin.yaml" --plugin-root . \
    --lang python --python-extensions-module weko_suite_ext \
    --out "$WORK/generated/${module}.py"
done

if [ "$PATCH_IGNORE" = 1 ]; then
  step "rig-only workaround F-1: pass evidence.ignore to the runner"
  uv run python "$EXAMPLES/patch_generated.py" "$WORK"/generated/*.py
fi

if [ "$BROWSER" = 1 ]; then
  step "Playwright browsers"
  if ! uv run python - <<'PY' 2>/dev/null
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    p.chromium.launch(headless=True).close()
PY
  then
    echo "default Chromium does not match Playwright's pinned revision; using a throwaway shim"
    uv run python - "$WORK/pw" <<'PY'
import os, re, sys
from pathlib import Path
from playwright.sync_api import sync_playwright

target = Path(sys.argv[1])
with sync_playwright() as p:
    try:
        p.chromium.launch(headless=True)
    except Exception as error:  # the message names the expected path
        wanted = re.search(r"Executable doesn't exist at (\S+)", str(error)).group(1)
base = Path(os.environ.get("PLAYWRIGHT_BROWSERS_PATH", "/opt/pw-browsers"))
rev = re.search(r"chromium_headless_shell-(\d+)", wanted).group(1)
have = sorted(base.glob("chromium_headless_shell-*"))[-1] / "chrome-linux"
dest = target / f"chromium_headless_shell-{rev}" / "chrome-headless-shell-linux64"
dest.mkdir(parents=True)
for item in have.iterdir():
    (dest / item.name).symlink_to(item)
(dest / "chrome-headless-shell").symlink_to("headless_shell")
(target / f"chromium_headless_shell-{rev}" / "INSTALLATION_COMPLETE").touch()
PY
    export PLAYWRIGHT_BROWSERS_PATH="$WORK/pw"
  fi
fi

step "run the generated tests (evidence: $EVIDENCE)"
mkdir -p "$EVIDENCE"
set +e
ATH_EVIDENCE_DIR="$EVIDENCE" uv run pytest -c pyproject.toml --rootdir . -p no:cacheprovider \
  -o python_files='*.py' -v "$WORK/generated"
PYTEST_STATUS=$?
set -e

step "evidence checks"
FAIL=0
check() { # check <description> <command...>
  local description="$1"; shift
  if "$@"; then echo "ok   $description"; else echo "FAIL $description"; FAIL=1; fi
}
no_raw_token() { ! grep -rqF -- "$RIG_TOKEN" "$EVIDENCE"; }
has_file() { find "$EVIDENCE" -type f -name "$1" | grep -q .; }
masked_header() { grep -rhi '"authorization"' "$EVIDENCE" | grep -q '\*'; }
check "tests passed" test "$PYTEST_STATUS" = 0
check "evidence tree exists" test -d "$EVIDENCE"
check "raw token absent from the evidence tree" no_raw_token
check "Authorization is masked in a saved exchange" masked_header
check "http exchange files present" has_file '*http-OP-SWORD-POST*.json'
check "app-log evidence present (via fake docker logs)" has_file '*app-log*'
check "db-records evidence present (via fake docker + helper snapshot)" has_file '*db-records*'
if [ "$BROWSER" = 1 ]; then
  check "screenshot present" has_file '*screenshot*.png'
  check "browser console evidence present" has_file '*console*.json'
  check "browser network evidence present" has_file '*network*.json'
  check "the intentional console error was captured" \
    grep -rqF "stub-admin: intentional console error" "$EVIDENCE"
fi

step "evidence tree"
(cd "$EVIDENCE" && find . -type f | sort | head -30; echo "  ... ($(find . -type f | wc -l) files)")
echo
echo "work directory: $WORK"
[ "$FAIL" = 0 ] && [ "$PYTEST_STATUS" = 0 ] || exit 1
echo "rig e2e passed (this proves the mechanics only, nothing about WEKO)"
